:sparkles: Add update command, logs command

diff --git a/jinx b/jinx
--- a/jinx
+++ b/jinx
@@ -1,37 +1,77 @@
 #!/usr/bin/env bash
 
-# Define colors and formats for making everything pretty.
-COLOR_RED="\033[0;31m"
-COLOR_RED_LIGHT="\033[1;31m"
-
-COLOR_GREEN="\033[0;32m"
-COLOR_GREEN_LIGHT="\033[1;32m"
-
-COLOR_ORANGE="\033[0;33m"
-COLOR_YELLOW="\033[1;33m"
-
-COLOR_BLUE="\033[0;34m"
-COLOR_BLUE_LIGHT="\033[1;34m"
-
-COLOR_PURPLE="\033[0;35m"
-COLOR_PURPLE_LIGHT="\033[1;35m"
-
-COLOR_CYAN="\033[0;36m"
-COLOR_CYAN_LIGHT="\033[1;36m"
-
-COLOR_GRAY="\033[1;30m"
-COLOR_GRAY_LIGHT="\033[0;37m"
-
-COLOR_BLACK="\033[0;30m"
-COLOR_WHITE="\033[1;37m"
-
-FORMAT_BOLD="\033[1m"
-FORMAT_UNDERLINE="\033[4m"
-
-FORMAT_END="\033[0m"
+JINX_VERSION="0.2.0"
 
 # Define location of configuration
-JINX_CONFIG_FILE="$HOME/.jinxrc"
+JINX_CONFIG_FOLDER="$HOME/.jinx"
+JINX_CONFIG_FILE="$JINX_CONFIG_FOLDER/config"
+
+# Create configuration file if it doesn't exist.
+if [[ ! -f $JINX_CONFIG_FILE ]]
+then
+    mkdir -p $JINX_CONFIG_FOLDER
+    cat <<EOF > $JINX_CONFIG_FILE
+#
+# .jinx/config
+# Configuration file for jinx
+#
+# Each configuration key must stand on its own line with no comments.
+# The comments above each variable explain their purpose.
+#
+
+# Where you nginx.conf and other files are located. Must end in /.
+nginx_path=/etc/nginx/
+
+# Where to find the configuration templates for new sites.
+# Gets appended to the nginx path. Must not contain slashes
+config_path=configurations
+
+# Which editor to use for editing sites
+editor=nano
+
+# Decides whether or not to use colored output.
+grumpy=0
+
+EOF
+
+    date +%s > "$JINX_CONFIG_FOLDER/last_update_check"
+
+    echo -e "\033[1;33mFirst run!\033[0m Creating default configuration in ~/.jinx/config"
+    echo "Pardon the interruption, we will now continue running your command."
+    echo ""
+fi
+
+JINX_IS_GRUMPY=$(grep -oh "grumpy=.*" $JINX_CONFIG_FILE | sed "s/grumpy=//")
+
+# Define colors and formats for making everything pretty.
+COLOR_RED=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[0;31m"`
+# COLOR_RED_LIGHT=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[1;31m"`
+
+COLOR_GREEN=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[0;32m"`
+# COLOR_GREEN_LIGHT=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[1;32m"`
+
+COLOR_ORANGE=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[0;33m"`
+COLOR_YELLOW=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[1;33m"`
+
+# COLOR_BLUE=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[0;34m"`
+# COLOR_BLUE_LIGHT=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[1;34m"`
+
+# COLOR_PURPLE=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[0;35m"`
+# COLOR_PURPLE_LIGHT=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[1;35m"`
+
+COLOR_CYAN=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[0;36m"`
+# COLOR_CYAN_LIGHT=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[1;36m"`
+
+# COLOR_GRAY=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[1;30m"`
+# COLOR_GRAY_LIGHT=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[0;37m"`
+
+# COLOR_BLACK=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[0;30m"`
+# COLOR_WHITE=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[1;37m"`
+
+FORMAT_BOLD=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[1m"`
+FORMAT_UNDERLINE=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[4m"`
+
+FORMAT_END=`[[ $JINX_IS_GRUMPY -eq 1 ]] && echo "" || echo "\033[0m"`
 
 # Functions
 function jinx_help {
@@ -40,6 +80,7 @@ function jinx_help {
     echo -e "${COLOR_CYAN}start${FORMAT_END}                                    start nginx service"
     echo -e "${COLOR_CYAN}restart${FORMAT_END}                                  restart nginx service"
     echo -e "${COLOR_CYAN}stop${FORMAT_END}                                     stop nginx service"
+    echo -e "${COLOR_CYAN}logs${FORMAT_END}                                     get nginx error logs"
     echo -e ""
     echo -e "${COLOR_CYAN}site activate <name> [--restart|-r]${FORMAT_END}      activate a site"
     echo -e "${COLOR_CYAN}site deactivate <name> [--restart|-r]${FORMAT_END}    deactivate a site"
@@ -47,8 +88,10 @@ function jinx_help {
     echo -e "${COLOR_CYAN}site create <name> [<template>]${FORMAT_END}          create a site from template"
     echo -e "${COLOR_CYAN}site edit <name>${FORMAT_END}                         edit a site .conf file with editor"
     echo -e ""
-    echo -e "${COLOR_CYAN}config <key>${FORMAT_END}                             get config value from ~/.jinxrc"
-    echo -e "${COLOR_CYAN}config <key> <value>${FORMAT_END}                     set config value in ~/.jinxrc"
+    echo -e "${COLOR_CYAN}config <key>${FORMAT_END}                             get config value from ~/.jinx/config"
+    echo -e "${COLOR_CYAN}config <key> <value>${FORMAT_END}                     set config value in ~/.jinx/config"
+    echo -e ""
+    echo -e "${COLOR_CYAN}update${FORMAT_END}                                   update jinx to the latest version"
     echo ""
 }
 
@@ -56,10 +99,10 @@ function jinx_service {
     OS="$(uname -a)"
     case "$OS" in
         *Ubuntu*)
-            sudo systemctl $1 nginx > /dev/null
+            sudo systemctl "$1" nginx > /dev/null
         ;;
         Darwin*)
-            sudo brew services $1 nginx > /dev/null
+            sudo brew services "$1" nginx > /dev/null
         ;;
         *)
             echo -e "${COLOR_RED}Failure.${FORMAT_END} Automatic $1 not supported on your system. Please $1 nginx manually."
@@ -84,6 +127,7 @@ function jinx_optional_restart {
 }
 
 function jinx_config_set {
+    local END_OF_PATH
     local JINX_CONFIG_VALUE="$2"
 
     if [[ -z "$1" ]] || [[ -z "$2" ]]
@@ -145,7 +189,6 @@ function jinx_site_activate {
     ln -sfn $FILE_PATH $NGINX_PATH/sites-enabled/ > /dev/null
     echo -e "${COLOR_GREEN}Success.${FORMAT_END} Activated site '$1'."
 
-    echo "$2"
     jinx_optional_restart "$2"
 
     exit 0
@@ -280,39 +323,118 @@ function jinx_site_delete {
     exit 1
 }
 
+function jinx_logs {
+    local NGINX_PATH=$(jinx_config_get "nginx_path")
+    local NGINX_CONFIG_FILE="$NGINX_PATH/nginx.conf"
+    local NGINX_LOGS=$(grep -oh "error_log .*" "$NGINX_CONFIG_FILE" | sed "s/^error_log //")
+
+    tail -f $(echo "$NGINX_LOGS" | tr -d ";")
+}
+
+function jinx_get_latest_release {
+    echo $(curl -s https://api.github.com/repos/pretzelhands/jinx/releases/latest)
+}
+
+function jinx_get_json_value {
+    echo $(echo $1 | python -c "import sys, json; print json.load(sys.stdin)['$2']")
+}
+
+# TODO: I need to make this prettier
+function jinx_get_yesterday_timestamp {
+    echo $(python -c "import time; from datetime import datetime, timedelta; yesterday=datetime.now()-timedelta(days=1); print str(time.mktime(yesterday.timetuple()))[:-2]")
+}
+
+function jinx_check_version {
+    local JINX_LAST_UPDATE_CHECK=$(cat "$JINX_CONFIG_FOLDER/last_update_check")
+    local JINX_LAST_UPDATE_LIMIT=$(jinx_get_yesterday_timestamp)
+
+    if [[ $JINX_LAST_UPDATE_CHECK -gt $JINX_LAST_UPDATE_LIMIT ]]
+    then
+        return
+    fi
+
+    local JINX_LATEST_RELEASE=$(jinx_get_latest_release)
+    local JINX_LATEST_VERSION=$(jinx_get_json_value "$JINX_LATEST_RELEASE" "tag_name")
+
+    if [[ "$JINX_VERSION" != "$JINX_LATEST_VERSION" ]]
+    then
+        echo -e "${COLOR_YELLOW}There is a new version of jinx available.${FORMAT_END}"
+        echo -e "Please run 'jinx update' to get the latest version"
+    fi
+}
+
+function jinx_update {
+    echo -n "Grabbing latest release from GitHub... "
+
+    local JINX_EXECUTABLE=$(which jinx)
+    local JINX_TMP="/var/tmp/jinx"
+    local JINX_LATEST_RELEASE=$(jinx_get_latest_release)
+    local JINX_LATEST_TARBALL=$(jinx_get_json_value "$JINX_LATEST_RELEASE" "tarball_url")
+    local JINX_LATEST_VERSION=$(jinx_get_json_value "$JINX_LATEST_RELEASE" "tag_name")
+
+    if [[ "$JINX_VERSION" == "$JINX_LATEST_VERSION" ]]
+    then
+        echo -e "${COLOR_GREEN}done.${FORMAT_END}\n${COLOR_GREEN}You are already using the latest version of jinx!${FORMAT_END}"
+        exit 0
+    fi
+
+    echo -e "${COLOR_GREEN}done.${FORMAT_END}"
+    echo -n "Grabbing latest tarball from GitHub... "
+    mkdir -p $JINX_TMP
+    mkdir -p $JINX_TMP/unpacked
+    curl -L "$JINX_LATEST_TARBALL" -o "$JINX_TMP/jinx.tar.gz" --silent
+    echo -e "${COLOR_GREEN}done.${FORMAT_END}"
+
+    echo -n "Unpacking jinx executable and installing ... "
+    tar xzf "$JINX_TMP/jinx.tar.gz" -C "$JINX_TMP/unpacked" --strip-components 1
+    mv "$JINX_TMP/unpacked/jinx" "$JINX_EXECUTABLE"
+    echo -e "${COLOR_GREEN}done.${FORMAT_END}"
+
+    rm -r /var/tmp/jinx
+    exit 0
+}
+
 #
 # Sanity checks
 #
 
-# Create configuration file if it doesn't exist.
-if [[ ! -f $JINX_CONFIG_FILE ]]
-then
-    echo -e "#\n# .jinxrc\n# Configuration file for jinx\n#\n# Each configuration key must stand on its own line with no comments.\n# The comments above each variable explain their purpose.\n#\n\n# Where you nginx.conf and other files are located. Must end in "/".\nnginx_path=/etc/nginx/\n\n# Where to find the configuration templates for new sites.\n# Gets appended to the nginx path. Must not contain slashes\nconfig_path=configurations\n\n# Which editor to use for editing sites\neditor=nano\n" >> $JINX_CONFIG_FILE
-    echo -e "${COLOR_YELLOW}First run!${FORMAT_END} Creating default configuration in ~/.jinxrc"
-    echo "Pardon the interruption, we will now continue running your command."
-    echo ""
-fi
-
 # We require at least one command
 if [[ -z "$1" ]]
-then
-    echo -e "${COLOR_RED}Please provide a command.${FORMAT_END}\n"
-    jinx_help
-    exit 1
-fi
-
-# Display help text
-if [[ "$1" == "help" ]]
 then
     echo ""
     jinx_help
     exit 0
 fi
 
+jinx_check_version
+
 # Process arguments in order
 for arg in "$@"
 do
     case $arg in
+        help)
+            jinx_help
+            exit 0
+        ;;
+        restart)
+            jinx_service "restart"
+        ;;
+        stop)
+            jinx_service "stop"
+        ;;
+        start)
+            jinx_service "start"
+        ;;
+        logs)
+            jinx_logs
+        ;;
+        update)
+            jinx_update
+        ;;
+        version)
+            echo -e "$JINX_VERSION"
+            exit 0
+        ;;
         config)
             if [[ -z "$2" ]]
             then
@@ -327,15 +449,6 @@ do
             then
                 jinx_config_set "$2" "$3"
             fi
-        ;;
-        restart)
-            jinx_service "restart"
-        ;;
-        stop)
-            jinx_service "stop"
-        ;;
-        start)
-            jinx_service "start"
         ;;
         site)
             if [[ "$2" == "activate" ]]
